### ISSUE TITLE
Doesn't work in 1.21

### ISSUE THREAD

**Issue by blue-pinapple** [R2bEEaton-Minecraft/CoreProtectTimeLapse#11]
Last time I tested it, it didn't work in 1.21
if you need the logs, I can test it again

**Comment by R2bEEaton** [comment]
> Last time I tested it, it didn't work in 1.21 if you need the logs, I can test it again

This has been graciously fixed by @heypr, please check the latest version!

**Comment by R2bEEaton** [comment]
This has been graciously fixed by @heypr, please check the latest version!
